/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import DAO.PacienteDAO;
import javax.swing.JOptionPane;
import model.Paciente;

/**
 *
 * @author lucasz
 */
public class AlterarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form aux
     * @param pac
     */
    public AlterarPaciente(Paciente pac) {
        initComponents();
        initComponents();
        jT_Nome.setText(pac.getNome());
        jT_End.setText(pac.getEndereco());
        jF_CPF.setText(pac.getCPF());
        jT_RG.setText(pac.getRG());
        
        String sexo = pac.getSexo();
        if(sexo.equals("F")){
            jR_F.setSelected(true);
        }
        else{
            jR_M.setSelected(true);
        }
        
        jS_Conv.setValue(pac.getCod_con());
        jS_Plano.setValue(pac.getCod_plano());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jT_Nome = new javax.swing.JTextField();
        jF_CPF = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jF_Telefone = new javax.swing.JFormattedTextField();
        jT_End = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jR_M = new javax.swing.JRadioButton();
        jR_F = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jT_RG = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jS_Plano = new javax.swing.JSpinner();
        jS_Conv = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(670, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(670, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 70, 20));

        jLabel3.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel3.setText("CPF:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 50, -1));

        jLabel4.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel4.setText("Telefone:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, -1));

        jLabel5.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel5.setText("Endereço:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, -1));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Alterar Dados Paciente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 530, 40));

        jT_Nome.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jT_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 520, 30));

        jF_CPF.setEditable(false);
        try {
            jF_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jF_CPF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jF_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 180, 30));

        jLabel7.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel7.setText("RG:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 40, 20));

        try {
            jF_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jF_Telefone.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jF_Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 180, -1));

        jT_End.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jT_End, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 520, 30));

        jLabel8.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel8.setText("Sexo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        buttonGroup1.add(jR_M);
        jR_M.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jR_M.setText("Masculino");
        getContentPane().add(jR_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 130, -1));

        buttonGroup1.add(jR_F);
        jR_F.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jR_F.setText("Feminino");
        getContentPane().add(jR_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 130, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar-como-48.png"))); // NOI18N
        jLabel9.setText("Salvar");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 120, 50));

        jT_RG.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jT_RG, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 180, -1));

        jLabel10.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel10.setText("Código Convênio");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel11.setText("Código Plano");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 130, -1));

        jS_Plano.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jS_Plano.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(jS_Plano, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 90, -1));

        jS_Conv.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jS_Conv.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(jS_Conv, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 90, -1));

        jLabel12.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair-48.png"))); // NOI18N
        jLabel12.setText("Sair");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        boolean confirm = true;
        
        String nome = jT_Nome.getText();
        if(nome.equals("")){
            confirm = false;
        }
        
        String endereco = jT_End.getText();
        if(endereco.equals("")){
            confirm = false;
        }
        
        String telefone = jF_Telefone.getText();
        if(telefone.replace("(","").replace(")","").replace("9","").replace("-","").equals("")){
            confirm = false;
        }
        
        String cpf = jF_CPF.getText();
        
        String rg = jT_RG.getText();
        if(rg.equals("")){
            confirm = false;
        }
        
        String sexo = "X";
        
        if(jR_F.isSelected()){
            sexo = "F";
        }
        
        else if(jR_M.isSelected()){
            sexo = "M";
        }
        
        else{
            confirm = false;
        }
        
        int cod_con = (int) jS_Conv.getValue();
        int cod_plano = (int) jS_Plano.getValue();
        
        if(confirm){
            Paciente pac = new Paciente();
            pac.setNome(nome);
            pac.setEndereco(endereco);
            pac.setCPF(cpf);
            pac.setRG(rg);
            pac.setSexo(sexo);
            pac.setCod_con(cod_con);
            pac.setCod_plano(cod_plano);
            
            int op = JOptionPane.showConfirmDialog(this,"Deseja realmente alterar os dados desse paciente?");
            
            if(op == 0){
                PacienteDAO dao = new PacienteDAO();
                dao.update(pac);
            }
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField jF_CPF;
    private javax.swing.JFormattedTextField jF_Telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jR_F;
    private javax.swing.JRadioButton jR_M;
    private javax.swing.JSpinner jS_Conv;
    private javax.swing.JSpinner jS_Plano;
    private javax.swing.JTextField jT_End;
    private javax.swing.JTextField jT_Nome;
    private javax.swing.JTextField jT_RG;
    // End of variables declaration//GEN-END:variables
}
