/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import DAO.Ficha_MedicaDAO;
import javax.swing.JOptionPane;
import model.Ficha_Medica;

/**
 *
 * @author lucasz
 */
public class AlterarFicha extends javax.swing.JFrame {

    /**
     * Creates new form AlterarFicha
     */
    public AlterarFicha(Ficha_Medica ficha) {
        initComponents();
        String cod = String.valueOf(ficha.getCod());
        jT_Cod.setText(cod);
        jF_Data.setText(ficha.getData_consulta());
        jT_Queixa.setText(ficha.getQueixa());
        jT_Ant.setText(ficha.getAntecedentes());
        jT_Hist.setText(ficha.getHistorico());
        jT_Hip.setText(ficha.getHipotese_diag());
        jT_Med.setText(ficha.getMedicacao());
        jT_ExA.setText(ficha.getExames_ap_sist());
        jT_ExC.setText(ficha.getExames_comp());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jF_Data = new javax.swing.JFormattedTextField();
        jT_Queixa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_Ant = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Hist = new javax.swing.JTextArea();
        jT_Hip = new javax.swing.JTextField();
        jT_Med = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_ExC = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jT_ExA = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jT_Cod = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setText("Alterar Ficha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel2.setText("Data:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel3.setText("Queixa:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel4.setText("Antecedentes:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel5.setText("Histórico:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel6.setText("Hipótese:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel7.setText("Medicação:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel8.setText("Exames em Ap.:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel9.setText("Exames Comp.:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        try {
            jF_Data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jF_Data.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jF_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 130, 30));

        jT_Queixa.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jT_Queixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 410, 30));

        jT_Ant.setColumns(20);
        jT_Ant.setFont(new java.awt.Font("Liberation Serif", 1, 14)); // NOI18N
        jT_Ant.setRows(5);
        jScrollPane2.setViewportView(jT_Ant);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 580, 80));

        jT_Hist.setColumns(20);
        jT_Hist.setFont(new java.awt.Font("Liberation Serif", 1, 14)); // NOI18N
        jT_Hist.setRows(5);
        jScrollPane1.setViewportView(jT_Hist);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 580, 70));

        jT_Hip.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jT_Hip, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 540, 40));

        jT_Med.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jT_Med, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 296, -1));

        jT_ExC.setColumns(20);
        jT_ExC.setFont(new java.awt.Font("Liberation Serif", 1, 14)); // NOI18N
        jT_ExC.setRows(5);
        jScrollPane3.setViewportView(jT_ExC);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 285, -1));

        jT_ExA.setColumns(20);
        jT_ExA.setFont(new java.awt.Font("Liberation Serif", 1, 14)); // NOI18N
        jT_ExA.setRows(5);
        jScrollPane4.setViewportView(jT_ExA);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 285, -1));

        jButton1.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar-como-48.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 190, 50));

        jT_Cod.setEditable(false);
        jT_Cod.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jT_Cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 80, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 780, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int cod = Integer.parseInt(jT_Cod.getText());
         
        boolean confirm = true;
        
        String aux[] = jF_Data.getText().split("/");
        String data = aux[2] +"-"+aux[1]+"-"+aux[0];
        if(data.replace("-", "").replace(" ","").equals("")){
            confirm = false;
        }
        
        String queixa = jT_Queixa.getText();
        if(queixa.equals("")){
            confirm = false;
        }
        
        String ant = jT_Ant.getText();
        if(ant.equals("")){
            confirm = false;
        }
        
        String hist = jT_Hist.getText();
        if(hist.equals("")){
            confirm = false;
        }
        
        String hip = jT_Hip.getText();
        if(hip.equals("")){
            confirm = false;
        }
        
        String med = jT_Med.getText();
        if(med.equals("")){
            confirm = false;
        }
        
        String exa = jT_ExA.getText();
        if(exa.equals("")){
            confirm = false;
        }
        
        String exc = jT_ExC.getText();
        if(exc.equals("")){
            confirm = false;
        }
        
        if(confirm){
            Ficha_Medica ficha = new Ficha_Medica();
            ficha.setCod(cod);
            ficha.setData_consulta(data);
            ficha.setQueixa(queixa);
            ficha.setAntecedentes(ant);
            ficha.setHistorico(hist);
            ficha.setHipotese_diag(hip);
            ficha.setMedicacao(med);
            ficha.setExames_ap_sist(exa);
            ficha.setExames_comp(exc);
            
            int op = JOptionPane.showConfirmDialog(this,"Deseja realmente alterar essa ficha?");
            
            if(op == 0){
                Ficha_MedicaDAO dao = new Ficha_MedicaDAO();
                dao.update(ficha);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jF_Data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jT_Ant;
    private javax.swing.JTextField jT_Cod;
    private javax.swing.JTextArea jT_ExA;
    private javax.swing.JTextArea jT_ExC;
    private javax.swing.JTextField jT_Hip;
    private javax.swing.JTextArea jT_Hist;
    private javax.swing.JTextField jT_Med;
    private javax.swing.JTextField jT_Queixa;
    // End of variables declaration//GEN-END:variables
}
