/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import DAO.ConsultaDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Consulta;

/**
 *
 * @author Aluno 22
 */
public class BusConsultas extends javax.swing.JInternalFrame {

    /**
     * Creates new form BusConsultas
     */
    public BusConsultas() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        jTable.setRowSorter(new TableRowSorter(model));
        readTable(new ConsultaDAO().readAll());
    }
    
    public void readTable(List<Consulta> dao){
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.setNumRows(0);
        
        for(Consulta c: dao){
            model.addRow(new Object[]{
                c.getCod(),
                c.getMedico(),
                c.getPaciente(),
                c.getData(),
                c.getHora_inicio(),
                c.getHora_final(),
                c.getSituacao()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jT_CRM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jF_CPF = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jF_Data = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jC_UF = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(640, 390));
        setPreferredSize(new java.awt.Dimension(640, 390));
        getContentPane().setLayout(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Buscar Consultas ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 460, 60));

        jLabel3.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel3.setText("CRM do Médico:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 30));

        jT_CRM.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanel1.add(jT_CRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 170, 30));

        jLabel4.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel4.setText("CPF do Cliente:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 140, 30));

        try {
            jF_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jF_CPF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanel1.add(jF_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 150, 30));

        jLabel5.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel5.setText("Data da Consulta: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 30));

        try {
            jF_Data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jF_Data.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jF_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jF_DataActionPerformed(evt);
            }
        });
        jPanel1.add(jF_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 130, 30));

        jTable.setFont(new java.awt.Font("Liberation Serif", 1, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Médico", "Paciente", "Data", "Hora Inicio", "Hora Fim", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 610, 140));

        jLabel10.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar-48.png"))); // NOI18N
        jLabel10.setText("Buscar ");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 130, 40));

        jC_UF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jC_UF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        jPanel1.add(jC_UF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 70, 29));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wallpaper.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 380));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 367);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        String crm = jT_CRM.getText();
        String cpf = jF_CPF.getText();
        String[] aux = jF_Data.getText().split("/");
        String data = aux[2] +"-"+aux[1]+"-"+aux[0];
        ConsultaDAO dao = new ConsultaDAO();
        if(!crm.equals("")){
            crm += "/" + jC_UF.getSelectedItem();
            readTable(dao.readForCRM(crm));
            
        }
        else if(!cpf.replace(".","").replace("-","").replace(" ","").equals("")){
            readTable(dao.readForCPF(cpf));
        } 
        else if(!data.replace("-","").replace(" ","").equals("")){
            readTable(dao.readForDate(data));
        }
        else{
            readTable(dao.readAll());
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jF_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jF_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jF_DataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jC_UF;
    private javax.swing.JFormattedTextField jF_CPF;
    private javax.swing.JFormattedTextField jF_Data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_CRM;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
