/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import DAO.MedicoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Medico;

/**
 *
 * @author Aluno 22
 */
public class BusMed extends javax.swing.JInternalFrame {

    /**
     * Creates new form busMed
     */
    public BusMed() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        jTable.setRowSorter(new TableRowSorter(model));
        
        readTable(new MedicoDAO().readAll());
    }
    
    public void readTable(List<Medico> dao){
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.setNumRows(0);
        
        for(Medico m: dao){
            model.addRow(new Object[]{
                m.getNome(),
                m.getCRM(),
                m.getEndereco(),
                m.getSexo()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jT_Nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jT_CRM = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jC_UF = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(640, 455));
        setPreferredSize(new java.awt.Dimension(640, 455));

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setText("Buscar Médicos ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 10, 270, 50);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Nome do Médico ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 130, 180, 40);

        jT_Nome.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jT_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NomeActionPerformed(evt);
            }
        });
        jPanel1.add(jT_Nome);
        jT_Nome.setBounds(190, 140, 210, 26);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setText("CRM do Médico");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 90, 140, 30);

        jT_CRM.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanel1.add(jT_CRM);
        jT_CRM.setBounds(190, 90, 210, 30);

        jTable.setFont(new java.awt.Font("Liberation Serif", 1, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CRM", "Endereço", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 193, 530, 170);

        jC_UF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jC_UF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        jPanel1.add(jC_UF);
        jC_UF.setBounds(420, 90, 71, 30);

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar-48.png"))); // NOI18N
        jLabel8.setText("Buscar");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 130, 120, 50);

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar-48.png"))); // NOI18N
        jLabel9.setText("Alterar");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(260, 370, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wallpaper.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, 0, 650, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NomeActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        String nome = jT_Nome.getText();
        String crm = jT_CRM.getText();
        
        if(!nome.equals("")){
            readTable(new MedicoDAO().readForName(nome));
        }
        
        else if(!crm.equals("")){
            crm += "/"+jC_UF.getSelectedItem();
            readTable(new MedicoDAO().readForCRM(crm));
        }
        
        else{
            readTable(new MedicoDAO().readAll());
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        int linha = jTable.getSelectedRow();
        if(linha != -1){
            String crm = (String) jTable.getValueAt(linha,1);
            List<Medico> medico = new MedicoDAO().readForCRM(crm);
            Medico med = medico.get(0);
            new AlterarMed(med).setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Selecione uma linha da tabela.");
        }
    }//GEN-LAST:event_jLabel9MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jC_UF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_CRM;
    private javax.swing.JTextField jT_Nome;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
