/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import DAO.PlanoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Plano;

/**
 *
 * @author lucasz
 */
public class BusPlano extends javax.swing.JInternalFrame {

    /**
     * Creates new form BusPlano
     */
    public BusPlano() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        jTable.setRowSorter(new TableRowSorter(model));
        
        readTable(new PlanoDAO().readAll());
    }
    
    public void readTable(List<Plano> dao){
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.setNumRows(0);
        
        for(Plano p: dao){
            model.addRow(new Object[]{
                p.getCod_con(),
                p.getCod(),
                p.getTipo(),
                p.getDesc()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jS_Plano = new javax.swing.JSpinner();
        jT_Tipo = new javax.swing.JTextField();
        jS_Conv = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jL_ap = new javax.swing.JLabel();
        jL_alt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMinimumSize(new java.awt.Dimension(570, 420));
        setPreferredSize(new java.awt.Dimension(570, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel1.setText("Tipo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel2.setText("Código Convênio:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel3.setText("Buscar Plano");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 280, 40));

        jLabel4.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel4.setText("Código Plano:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jTable.setFont(new java.awt.Font("Liberation Serif", 1, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Conv.", "Cod. Plano", "Tipo", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 620, 188));

        jS_Plano.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jS_Plano.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(jS_Plano, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 77, -1));

        jT_Tipo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jT_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 230, 30));

        jS_Conv.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jS_Conv.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(jS_Conv, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 72, -1));

        jLabel6.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar-48.png"))); // NOI18N
        jLabel6.setText("Buscar");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 130, 40));

        jL_ap.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jL_ap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apagar-48.png"))); // NOI18N
        jL_ap.setText("Apagar");
        jL_ap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_apMouseClicked(evt);
            }
        });
        getContentPane().add(jL_ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        jL_alt.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jL_alt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar-48.png"))); // NOI18N
        jL_alt.setText("Alterar");
        jL_alt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_altMouseClicked(evt);
            }
        });
        getContentPane().add(jL_alt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jL_apMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_apMouseClicked
        int linha = jTable.getSelectedRow();
        
        if(linha != -1){
            int cod = (int) jTable.getValueAt(linha ,1);
            if(cod != 1){
                PlanoDAO dao = new PlanoDAO();
                dao.delete(cod);
            }
            else{
                JOptionPane.showMessageDialog(this,"Não pode apagar o plano 1.");
            }
        }
        
        else{
            JOptionPane.showMessageDialog(this,"Selecione uma linha da tabela.");
        }
    }//GEN-LAST:event_jL_apMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        String tipo = jT_Tipo.getText();
        int cod_conv = (int) jS_Conv.getValue();
        int cod_plano = (int) jS_Plano.getValue();
        
        if(!tipo.equals("")){
            readTable(new PlanoDAO().readForTipo(tipo));
        }
        else if(cod_conv > 1){
            readTable(new PlanoDAO().readForCod_con(cod_conv));
        }
        else if(cod_plano > 1){
            readTable(new PlanoDAO().readForCod(cod_plano));
        }
        else{
            readTable(new PlanoDAO().readAll());
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jL_altMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_altMouseClicked
        int linha = jTable.getSelectedRow(); 
        if (linha != -1){
            int cod = (int) jTable.getValueAt(linha,1);
            if(cod == 1){
                JOptionPane.showMessageDialog(this,"Plano 1 não pode ser alterado.");
            }
            else{
                List<Plano> p = new PlanoDAO().readForCod(cod);
                Plano plano = p.get(0);
                new AlterarPlano(plano).setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Selecione uma linha da tabela.");
        }
        
    }//GEN-LAST:event_jL_altMouseClicked

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        
    }//GEN-LAST:event_jTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_alt;
    private javax.swing.JLabel jL_ap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jS_Conv;
    private javax.swing.JSpinner jS_Plano;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_Tipo;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
