/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import DAO.MedicoDAO;
import javax.swing.JOptionPane;
import model.Medico;

/**
 *
 * @author Aluno 22
 */
public class CadMedico extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadMedico
     */
    public CadMedico() {
        initComponents();
    }
    public void limpar(){
        jT_Nome.setText("");
        jF_CPF.setText("");
        jT_RG.setText("");
        jT_CRM.setText("");
        jF_Telefone.setText("");
        jT_End.setText("");
        jP_Senha.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jT_Nome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jF_CPF = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jF_Telefone = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jT_End = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jP_Senha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jR_M = new javax.swing.JRadioButton();
        jR_F = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jT_CRM = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jT_RG = new javax.swing.JTextField();
        jC_UF = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(600, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro médico ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 380, 51));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Nome ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 30));

        jT_Nome.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jT_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NomeActionPerformed(evt);
            }
        });
        getContentPane().add(jT_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 480, 30));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setText("CPF");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 50, 30));

        try {
            jF_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jF_CPF.setText("");
        jF_CPF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jF_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 240, 30));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel6.setText("RG");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 30, 30));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel7.setText("Telefone ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 30));

        try {
            jF_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jF_Telefone.setText("");
        jF_Telefone.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jF_Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 160, 30));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel8.setText("Endereço ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, -1));

        jT_End.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jT_End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_EndActionPerformed(evt);
            }
        });
        getContentPane().add(jT_End, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 450, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mostrar-a-senha-24.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 30, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel9.setText("Senha ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 40));

        jP_Senha.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jP_Senha.setEchoChar('*');
        jP_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jP_SenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jP_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 190, 30));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel10.setText("Sexo ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jR_M.setBackground(null);
        buttonGroup1.add(jR_M);
        jR_M.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jR_M.setText("Masculino");
        getContentPane().add(jR_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 120, -1));

        buttonGroup1.add(jR_F);
        jR_F.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jR_F.setText("Feminino");
        getContentPane().add(jR_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 120, -1));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel14.setText("CRM");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 59, 15));

        jT_CRM.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jT_CRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 300, 30));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel15.setText("UF");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar-como-48.png"))); // NOI18N
        jLabel11.setText("Salvar");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 140, 50));

        jT_RG.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(jT_RG, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 170, 30));

        jC_UF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jC_UF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        getContentPane().add(jC_UF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 154, 90, 40));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpar-48.png"))); // NOI18N
        jLabel4.setText("Limpar");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NomeActionPerformed

    private void jT_EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_EndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_EndActionPerformed

    private void jP_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jP_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_SenhaActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        boolean confirm = true;
        
        String nome = jT_Nome.getText();
        if(nome.equals("")){
            confirm = false;
        }
        
        String cpf = jF_CPF.getText();
        if(cpf.replace(".", "").replace(" ","").replace("-","").equals("")){
            confirm = false;
        }
        
        String rg = jT_RG.getText();
        if(rg.equals("")){
            confirm = false;
        }
        
        String crm = jT_CRM.getText();
        String uf = (String) jC_UF.getSelectedItem();
        if(crm.equals("")){
            confirm = false;
        }
        else{
            crm += "/"+uf;
        }
        
        String telefone = jF_Telefone.getText();
        if(telefone.replace("(","").replace(")","").replace(" ","").replace("9","").replace("-","").equals("")){
            confirm = false;
        }
        
        String endereco = jT_End.getText();
        if(endereco.equals("")){
            confirm = false;
        }
        
        String senha = new String(jP_Senha.getPassword());
        if(senha.equals("")){
            confirm = false;
        }
        
        String sexo = "X";
        if(jR_F.isSelected()){
            sexo = "F";
        }
        else if(jR_M.isSelected()){
            sexo = "M";
        }
        else{
            confirm = false;
        }
        if(confirm){
            Medico med = new Medico();
            med.setNome(nome);
            med.setCPF(cpf);
            med.setRG(rg);
            med.setCRM(crm);
            med.setTelefone(telefone);
            med.setEndereco(endereco);
            med.setSexo(sexo);
            med.setSenha(senha);
            int op = JOptionPane.showConfirmDialog(this, "Deseja realmente cadastrar esse médico?");
            if(op == 0){
                MedicoDAO dao =  new MedicoDAO();
                dao.insert(med);
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(this,"Médico não será cadastrado.");
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Alguma informação não foi preenchida.");
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        if(jP_Senha.getEchoChar() == '*'){
            jP_Senha.setEchoChar('\u0000');
        }else{
            jP_Senha.setEchoChar('*');
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        limpar();
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jC_UF;
    private javax.swing.JFormattedTextField jF_CPF;
    private javax.swing.JFormattedTextField jF_Telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jP_Senha;
    private javax.swing.JRadioButton jR_F;
    private javax.swing.JRadioButton jR_M;
    private javax.swing.JTextField jT_CRM;
    private javax.swing.JTextField jT_End;
    private javax.swing.JTextField jT_Nome;
    private javax.swing.JTextField jT_RG;
    // End of variables declaration//GEN-END:variables
}
