/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import DAO.PacienteDAO;
import javax.swing.JOptionPane;
import model.Paciente;

/**
 *
 * @author Aluno 22
 */
public class CadPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form cadBuscar
     */
    public CadPaciente() {
        initComponents();
    }
    public void limpar(){
        jT_Nome.setText("");
        jT_End.setText("");
        jF_Tel.setText("");
        jF_CPF.setText("");
        jT_RG.setText("");
        jS_Conv.setValue(1);
        jS_Plano.setValue(1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jT_Nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jT_End = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jF_Tel = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jF_CPF = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jR_M = new javax.swing.JRadioButton();
        jR_F = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jT_RG = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jS_Plano = new javax.swing.JSpinner();
        jS_Conv = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(650, 455));
        setPreferredSize(new java.awt.Dimension(650, 455));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpar-48.png"))); // NOI18N
        jLabel9.setText("Limpar");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 120, 50));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro Paciente  ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 540, 40));

        jLabel3.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel3.setText("Nome: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 30));

        jT_Nome.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanel1.add(jT_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 520, 30));

        jLabel4.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel4.setText("Endereço: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, 20));

        jT_End.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanel1.add(jT_End, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 490, 30));

        jLabel5.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel5.setText("Telefone: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 90, -1));

        try {
            jF_Tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jF_Tel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanel1.add(jF_Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 160, 30));

        jLabel6.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel6.setText("CPF");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 40, 20));

        try {
            jF_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jF_CPF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanel1.add(jF_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 160, 30));

        jLabel7.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel7.setText("RG");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 30, 30));

        jLabel8.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel8.setText("Sexo ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 50, 30));

        buttonGroup1.add(jR_M);
        jR_M.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jR_M.setText("Masculino");
        jPanel1.add(jR_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 120, -1));

        buttonGroup1.add(jR_F);
        jR_F.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jR_F.setText("Feminino");
        jR_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR_FActionPerformed(evt);
            }
        });
        jPanel1.add(jR_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 110, -1));

        jLabel11.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar-como-48.png"))); // NOI18N
        jLabel11.setText("Salvar ");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 120, 50));

        jT_RG.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanel1.add(jT_RG, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 200, 30));

        jLabel13.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel13.setText("Código Convênio");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 160, -1));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel14.setText("Código Plano");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 130, -1));

        jS_Plano.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jS_Plano.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(jS_Plano, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 70, 30));

        jS_Conv.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jS_Conv.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(jS_Conv, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wallpaper.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 4, 650, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        boolean confirm = true;
        
        String nome = jT_Nome.getText();
        if(nome.equals("")){
            confirm = false;
        }
        
        String endereco = jT_End.getText();
        if(endereco.equals("")){
            confirm = false;
        }
        
        String telefone = jF_Tel.getText();
        if(telefone.replace("(","").replace(")","").replace(" ","").replace("9","").equals("")){
            confirm = false;
        }
        
        String cpf = jF_CPF.getText();
        if(cpf.replace(".","").replace("-","").replace(" ","").equals("")){
            confirm = false;
        }
        
        String rg = jT_RG.getText();
        if(rg.equals("")){
            confirm = false;
        }
        
        String sexo = "X";
        if(jR_F.isSelected()){
            sexo = "F";
        }
        else if(jR_M.isSelected()){
            sexo = "M";
        }
        else{
            confirm = false;
        }
        
        int cod_con = (int) jS_Conv.getValue();
        int cod_plano = (int) jS_Plano.getValue();
        
        if(confirm){
            Paciente pac = new Paciente();
            pac.setNome(nome);
            pac.setEndereco(endereco);
            pac.setTelefone(telefone);
            pac.setCPF(cpf);
            pac.setRG(rg);
            pac.setSexo(sexo);
            pac.setCod_con(cod_con);
            pac.setCod_plano(cod_plano);
            int op = JOptionPane.showConfirmDialog(this,"Deseja realmente cadastrar esse paciente?");
            if(op == 0){
                PacienteDAO dao = new PacienteDAO();
                dao.insert(pac);
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(this,"Paciente não será cadastrado.");
            }
        }
        
        else{
            JOptionPane.showMessageDialog(this,"Alguma informaçao não foi preenchida.");
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jR_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR_FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jR_FActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        limpar();
    }//GEN-LAST:event_jLabel9MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField jF_CPF;
    private javax.swing.JFormattedTextField jF_Tel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jR_F;
    private javax.swing.JRadioButton jR_M;
    private javax.swing.JSpinner jS_Conv;
    private javax.swing.JSpinner jS_Plano;
    private javax.swing.JTextField jT_End;
    private javax.swing.JTextField jT_Nome;
    private javax.swing.JTextField jT_RG;
    // End of variables declaration//GEN-END:variables
}
